# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fridayai.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_friday(object):
    def setupUi(self, friday):
        friday.setObjectName("friday")
        friday.resize(1420, 900)
        self.centralwidget = QtWidgets.QWidget(friday)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -50, 1551, 1011))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("iron.gif"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1160, 840, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1270, 840, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 411, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("start.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(810, 110, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transprant;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1110, 110, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transprant;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        friday.setCentralWidget(self.centralwidget)

        self.retranslateUi(friday)
        QtCore.QMetaObject.connectSlotsByName(friday)

    def retranslateUi(self, friday):
        _translate = QtCore.QCoreApplication.translate
        friday.setWindowTitle(_translate("friday", "MainWindow"))
        self.pushButton.setText(_translate("friday", "Run"))
        self.pushButton_2.setText(_translate("friday", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    friday = QtWidgets.QMainWindow()
    ui = Ui_friday()
    ui.setupUi(friday)
    friday.show()
    sys.exit(app.exec_())
